package com.echosphere.backend.controller;

import com.echosphere.backend.dto.TranscriptResponse;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api")
public class TranscriptionController {

    @PostMapping("/transcribe")
    public TranscriptResponse transcribe() {

        Authentication auth = SecurityContextHolder.getContext().getAuthentication();

        if (auth == null || !auth.isAuthenticated()) {
            throw new RuntimeException("Unauthorized");
        }

        String email = auth.getName(); // extracted from JWT

        return new TranscriptResponse(
                "completed",
                "This is a sample transcription generated by EchoSphere AI for " + email,
                0.93
        );
    }
}
