package com.echosphere.backend.service;

import com.echosphere.backend.config.GeminiConfig;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

@Service
public class GeminiService {

    private final GeminiConfig config;
    private final HttpClient client = HttpClient.newHttpClient();
    private final ObjectMapper objectMapper = new ObjectMapper();

    public GeminiService(GeminiConfig config) {
        this.config = config;
    }

    public String generateText(String prompt) {
        try {
            String body = """
                    {
                      "contents": [
                        {
                          "parts": [
                            { "text": "%s" }
                          ]
                        }
                      ]
                    }
                    """.formatted(prompt);

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(
                            "https://generativelanguage.googleapis.com/v1/"
                                    + config.getModel()
                                    + ":generateContent?key="
                                    + config.getApiKey()))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(body))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            
            System.out.println("=== Gemini raw response ===");
            System.out.println(response.body());
            System.out.println("=== End Gemini response ===");

            // 🔥 Parse Gemini JSON
            JsonNode root = objectMapper.readTree(response.body());

            JsonNode textNode = root
                    .path("candidates")
                    .path(0)
                    .path("content")
                    .path("parts")
                    .path(0)
                    .path("text");

            if (textNode.isMissingNode()) {
                return "No response generated by Gemini.";
            }

            return textNode.asText();

        } catch (Exception e) {
            throw new RuntimeException("Gemini API error", e);
        }
    }

    public String[] generateChunks(String prompt) {
        String fullText = generateText(prompt);

        // simple chunking (later replaced by true streaming)
        int chunkSize = 30;
        int len = fullText.length();

        int parts = (int) Math.ceil((double) len / chunkSize);
        String[] chunks = new String[parts];

        for (int i = 0; i < parts; i++) {
            int start = i * chunkSize;
            int end = Math.min(start + chunkSize, len);
            chunks[i] = fullText.substring(start, end);
        }

        return chunks;
    }

}
